'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Check,ChevronRight,CircleAlert,GitBranch,Lightbulb,LockKeyhole,Play,RotateCcw,TerminalSquare,Trophy} from 'lucide-react';
import {executeGit,type RepoState} from '../lib/git-engine';
import {missions,type Mission} from '../lib/missions';
import {canAccessMission,loadProgress,newProgress,resetWorkflow,saveProgress} from '../lib/progress';
import {evaluateConceptAnswer} from '../lib/concept-validation';
type Feedback={tone:'idle'|'success'|'warning'|'error';title:string;text:string};
type Progress={missionIndex:number;stepIndex:number;completed:number[];repo:RepoState;answers:Record<string,string>};
const KEY='faex-git-lab-progress-v1',fresh=():Progress=>newProgress();
export default function Home(){const[p,setP]=useState<Progress>(fresh),[ready,setReady]=useState(false),[input,setInput]=useState(''),[feedback,setFeedback]=useState<Feedback>({tone:'idle',title:'Sua vez',text:'Digite o comando mostrado para começar.'}),[pop,setPop]=useState(false),[student,setStudent]=useState('');const ref=useRef<HTMLInputElement>(null);const mission=missions[p.missionIndex]||missions.at(-1)!,step=mission.steps[p.stepIndex]||mission.steps.at(-1)!,done=p.completed.includes(p.missionIndex),allDone=p.completed.length===missions.length;
useEffect(()=>{queueMicrotask(()=>{setP(loadProgress(localStorage,KEY,missions.length));setReady(true)})},[]);useEffect(()=>{if(ready)saveProgress(localStorage,KEY,p)},[p,ready]);
function success(repo=p.repo,answer?:string,review?:Feedback){if(p.stepIndex===mission.steps.length-1){setP(x=>({...x,repo,answers:answer?{...x.answers,[mission.id]:answer}:x.answers,completed:[...new Set([...x.completed,x.missionIndex])]}));setFeedback(review??{tone:'success',title:'Etapa concluída!',text:mission.success});setPop(true);setTimeout(()=>setPop(false),650)}else{setP(x=>({...x,repo,stepIndex:x.stepIndex+1}));setFeedback({tone:'success',title:'Muito bem!',text:mission.steps[p.stepIndex+1].instruction})}}
function run(){const cmd=input.trim();if(!cmd)return;const r=executeGit(p.repo,cmd);setInput('');if(!r.ok){setP(x=>({...x,repo:{...x.repo,history:r.state.history}}));setFeedback({tone:'error',title:'Não deu certo ainda',text:r.message});return}if(mission.type!=='git'||cmd.toLowerCase()!==step.expected?.toLowerCase()){setP(x=>({...x,repo:{...x.repo,history:r.state.history}}));setFeedback({tone:'warning',title:'Comando válido, mas fora de ordem',text:`Complete esta etapa com: ${step.expected}`});return}success(r.state)}
function answer(){const value=input.trim(),result=evaluateConceptAnswer(value,step.keywords??[]);if(result==='too-short'){setFeedback({tone:'error',title:'Falta um pouco',text:'Escreva ao menos uma palavra ou ideia curta.'});return}setInput('');if(result==='review'){success(p.repo,value,{tone:'warning',title:'Resposta aceita com ressalva',text:'A ideia foi registrada. Compare com o exemplo para deixá-la mais específica.'});return}success(p.repo,value)}function executeEntry(){if(mission.type==='git')run();else answer()}
function next(){if(p.missionIndex===missions.length-1){setP(x=>({...x,completed:missions.map((_,i)=>i)}));return}const n=p.missionIndex+1;setP(x=>({...x,missionIndex:n,stepIndex:0}));setFeedback({tone:'idle',title:'Nova missão',text:missions[n].steps[0].instruction});setTimeout(()=>ref.current?.focus(),50)}
function reset(){setP(resetWorkflow());setInput('');setStudent('');setFeedback({tone:'idle',title:'Laboratório reiniciado',text:missions[0].steps[0].instruction});setTimeout(()=>ref.current?.focus(),50)}
function select(i:number){if(!canAccessMission(p.completed,i)||p.completed.includes(i))return;setP(x=>({...x,missionIndex:i}));setFeedback({tone:'idle',title:'Missão selecionada',text:missions[i].steps[p.stepIndex]?.instruction??missions[i].steps[0].instruction})}
if(!ready)return <main className="loading">Preparando o laboratório…</main>;
return <main className="app-shell"><header className="topbar"><div className="brand"><span className="logo-mark"><GitBranch/></span><div><strong>FAEX Git Lab</strong><small>Engenharia de Software</small></div></div><div className="header-progress"><div><span>Seu progresso</span><b>{p.completed.length}/{missions.length}</b></div><div className="progress-track"><i style={{width:`${p.completed.length/missions.length*100}%`}}/></div></div><button className="button ghost" onClick={reset}><RotateCcw/> Reiniciar laboratório</button></header>
<div className="workspace"><aside className="sidebar"><div className="side-title"><BookOpen/> MISSÕES</div><nav>{missions.map((m,i)=>{const completed=p.completed.includes(i),locked=i>p.completed.length;return <button key={m.id} onClick={()=>select(i)} disabled={locked||completed} className={`mission-link ${i===p.missionIndex?'active':''} ${completed?'done':''}`}><span className="mission-number">{completed?<Check/>:locked?<LockKeyhole/>:i+1}</span><span><small>{m.group}</small>{m.title}</span>{!locked&&!completed&&<ChevronRight/>}</button>})}</nav></aside>
<section className="lesson">{allDone?<Certificate student={student} setStudent={setStudent} commands={p.repo.history.length}/>:<><div className="mission-heading"><span className="eyebrow">MISSÃO {p.missionIndex+1} · ETAPA {p.stepIndex+1} DE {mission.steps.length}</span><h1>{mission.title}</h1><p>{step.instruction}</p></div><div className="expected-card"><span>FAÇA AGORA</span><code>{mission.type==='git'?step.expected:step.placeholder}</code><small>{mission.type==='git'?'Digite este comando no terminal.':'Escreva uma resposta curta.'}</small></div>{mission.type==='git'&&<aside className="why-card"><Lightbulb/><div><strong>Por que usar no projeto?</strong><p>{step.why}</p></div></aside>}
{mission.type==='git'?<CommitTree repo={p.repo} pop={pop}/>:<ConceptVisual mission={mission}/>}<section className={`terminal ${mission.type==='concept'?'concept-terminal':''}`}><div className="terminal-title"><span><i className="dot red"/><i className="dot yellow"/><i className="dot green"/></span><b>{mission.type==='git'?'TERMINAL SIMULADO':'SUA RESPOSTA'}</b><span>{mission.type==='git'?'ENTER para executar':'Resposta curta'}</span></div>{mission.type==='git'&&<div className="terminal-history" aria-live="polite">{p.repo.history.slice(-5).map((h,i)=><div className="history-entry" key={`${h.command}-${i}`}><div className="history-command"><span>aluno@faex:~/projeto $</span><code>{h.command}</code></div><small>{h.output}</small></div>)}</div>}<div className="command-row"><label className="prompt" htmlFor="terminal-command">{mission.type==='git'?<><span>aluno@faex:~/projeto</span> $</>:'✎'}</label><input id="terminal-command" ref={ref} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')executeEntry()}} placeholder={mission.type==='git'?'Digite um comando Git…':step.placeholder}/><button onClick={executeEntry}><Play/>{mission.type==='git'?'Executar':'Verificar'}</button></div></section>
{feedback.tone!=='idle'&&<section className={`feedback ${feedback.tone}`} role="status"><div className="feedback-icon">{feedback.tone==='success'?<Check/>:feedback.tone==='error'?<CircleAlert/>:<TerminalSquare/>}</div><div><strong>{feedback.title}</strong><p>{feedback.text}</p></div>{done&&<button className="button primary" onClick={next}>{p.missionIndex===missions.length-1?'Ver certificado':'Próxima missão'} <ChevronRight/></button>}</section>}</>}</section></div><footer><span>FAEX · Engenharia de Software</span><span>Simulação acadêmica de Git</span></footer></main>}
function CommitTree({repo,pop}:{repo:RepoState;pop:boolean}){const visible=repo.commits.slice(-6),viewWidth=visible.length===1?360:visible.length===2?520:760,padding=visible.length<3?92:78,gap=visible.length===1?0:(viewWidth-padding*2)/(visible.length-1);const lane=(branch:string)=>branch==='main'?128:branch==='feature-requisitos'?166:194;return <section className="tree-card"><div className="tree-label"><span><GitBranch/> ÁRVORE DE COMMITS</span><span>● commit &nbsp; ◆ branch atual</span></div><div className="tree-canvas"><svg viewBox={`0 0 ${viewWidth} 230`} role="img" aria-label="Árvore visual de commits e branches">{visible.slice(1).map((c,i)=>{const prev=visible[i],x1=padding+i*gap,x2=padding+(i+1)*gap,y1=lane(prev.branch),y2=lane(c.branch);return <path key={c.id} d={`M${x1},${y1} C${x1+gap*.42},${y1} ${x2-gap*.42},${y2} ${x2},${y2}`} className="branch-line"/>})}{visible.map((c,i)=>{const x=visible.length===1?viewWidth/2:padding+i*gap,y=lane(c.branch),isHead=c.id===repo.head,branches=Object.entries(repo.branches).filter(([,id])=>id===c.id).sort(([a],[b])=>a===repo.currentBranch?-1:b===repo.currentBranch?1:a.localeCompare(b));return <g key={c.id} className={pop&&c.id===repo.commits.at(-1)?.id?'pop':''}><circle cx={x} cy={y} r="23" className={isHead?'commit current':'commit'}/><circle cx={x} cy={y} r="7" fill="white"/><text x={x} y={y+43} className="commit-id" textAnchor="middle">{c.id}</text><text x={x} y={y+62} className="commit-msg" textAnchor="middle">{c.message.length>18?`${c.message.slice(0,17)}…`:c.message}</text>{branches.map(([name],n)=>{const width=Math.min(170,Math.max(94,name.length*8+28)),badgeY=24+n*34,badgeX=Math.max(8,Math.min(viewWidth-8-width,x-width/2));return <g key={name}><rect x={badgeX} y={badgeY} width={width} height="28" rx="14" className={name===repo.currentBranch?'branch-pill active':'branch-pill'}/><text x={badgeX+width/2} y={badgeY+19} className="branch-name" textAnchor="middle">{name}</text>{name===repo.currentBranch&&n===0&&<text x={badgeX+width/2} y={badgeY-8} className="head-label" textAnchor="middle">HEAD ↓</text>}</g>})}</g>})}</svg></div><div className="tree-status"><span>Branch atual</span><b>◆ {repo.currentBranch}</b><span>HEAD</span><code>→ {repo.head}</code></div></section>}
function ConceptVisual({mission}:{mission:Mission}){return <section className="concept-card"><div className="concept-icon">{mission.icon}</div><div><span>CONCEITO EM FOCO</span><h2>{mission.title}</h2><p>{mission.objective}</p></div><div className="concept-example"><small>EXEMPLO</small>{mission.example}</div></section>}
function Certificate({student,setStudent,commands}:{student:string;setStudent:(v:string)=>void;commands:number}){return <section className="certificate-wrap"><div className="certificate"><div className="award"><Trophy/></div><span className="eyebrow">SIMULAÇÃO CONCLUÍDA</span><h1>Parabéns!</h1><p>Você concluiu a Simulação Prática de Git e GitHub — FAEX.</p><label>Nome do aluno<input value={student} onChange={e=>setStudent(e.target.value)} placeholder="Digite seu nome"/></label><div className="cert-stats"><div><b>{missions.length}</b><span>missões concluídas</span></div><div><b>{commands}</b><span>comandos praticados</span></div><div><b>{new Date().toLocaleDateString('pt-BR')}</b><span>data de conclusão</span></div></div><button className="button primary print" onClick={()=>window.print()} disabled={!student.trim()}><Trophy/> Imprimir certificado</button><small>Esta é uma certificação acadêmica simulada e não substitui uma certificação oficial do GitHub.</small></div></section>}

