export type MissionStep={instruction:string;expected?:string;placeholder?:string;keywords?:string[];hint?:string;why?:string};
export type Mission={id:string;title:string;group:string;type:'git'|'concept';objective:string;success:string;steps:MissionStep[];icon:string;example:string};
const commandWhy=(command:string)=>{
 if(command.startsWith('git commit'))return 'No projeto real, o commit cria um ponto seguro e registra o motivo da alteração para toda a equipe.';
 if(command.startsWith('git branch'))return 'No dia a dia, uma branch separa uma tarefa nova sem colocar a versão principal do projeto em risco.';
 if(command.startsWith('git switch main'))return 'Você volta à versão principal antes de entregar e integrar um trabalho concluído.';
 if(command.startsWith('git switch'))return 'Trocar de branch coloca você no contexto certo da tarefa em que vai trabalhar.';
 if(command==='git add .')return 'Antes do commit, você seleciona as alterações revisadas que realmente farão parte da próxima versão.';
 if(command.startsWith('git merge'))return 'O merge reúne na versão principal uma funcionalidade ou correção que já foi concluída.';
 if(command==='git log')return 'A equipe consulta o histórico para entender o que mudou, em qual ordem e por qual motivo.';
 return 'Este comando ajuda a manter o trabalho da equipe organizado e rastreável.';
};
const git=(id:string,title:string,objective:string,commands:string[],success:string):Mission=>({id,title,group:'PRÁTICA GIT',type:'git',objective,success,icon:'⌘',example:'Observe a árvore mudar a cada comando.',steps:commands.map((expected,i)=>({expected,instruction:i===0?objective:`Agora execute: ${expected}`,why:commandWhy(expected)}))});
const concept=(id:string,title:string,objective:string,placeholder:string,keywords:string[],example:string):Mission=>({id,title,group:'ENGENHARIA DE SOFTWARE',type:'concept',objective,success:'Resposta registrada. Conceito aprendido!',icon:'◆',example,steps:[{instruction:objective,placeholder,keywords,hint:`Tente algo parecido com: ${example}`} ]});
export const missions:Mission[]=[
git('commit','Criar um commit','Registre uma versão do projeto.',['git commit -m "primeiro commit"'],'Commit criado. Esta versão ficou salva.'),git('branch','Criar uma branch','Crie uma linha independente de trabalho.',['git branch feature-requisitos'],'Branch criada sem mudar sua posição.'),git('switch','Mudar de branch','Entre na branch que você criou.',['git switch feature-requisitos'],'Agora você está na nova branch.'),git('change','Registrar uma alteração','Prepare a alteração para o commit.',['git add .','git commit -m "adiciona requisitos"'],'Alteração registrada na feature.'),git('merge','Integrar uma branch','Volte para main e integre o trabalho.',['git switch main','git merge feature-requisitos'],'Feature integrada à branch principal.'),git('log','Consultar o histórico','Veja os commits já realizados.',['git log'],'Histórico consultado com sucesso.'),git('fix','Simular uma correção','Crie e integre uma correção.',['git branch correcao','git switch correcao','git add .','git commit -m "corrige requisito"','git switch main','git merge correcao'],'Correção integrada. Fluxo completo!'),
concept('problem','Problema e oportunidade','Descreva um problema real em uma frase.','Alunos perdem prazos porque…',['porque','dificuldade','perdem'],'Alunos perdem prazos porque os avisos ficam espalhados.'),concept('users','Usuários','Diga quem usará a solução.','Os usuários principais são…',['aluno','professor','usuário'],'Os usuários principais são alunos da graduação.'),concept('mvp','MVP','Escreva a menor entrega que já gera valor.','A primeira versão deve…',['permitir','mostrar','registrar'],'A primeira versão deve mostrar prazos em uma lista.'),concept('risks','Riscos','Indique um risco do projeto.','Um risco é…',['risco','atraso','falha','falta'],'Um risco é a baixa adesão dos alunos.'),concept('dod','Definition of Done','Diga quando uma tarefa pode ser considerada pronta.','A tarefa está pronta quando…',['test','revis','aceit','funciona'],'A tarefa está pronta quando foi testada e aceita.'),concept('process','Processo de software','Escreva uma etapa do processo de software.','Uma etapa é…',['planej','desenvol','test','requis'],'Uma etapa é testar a solução.'),concept('scope','Escopo','Defina algo que faz parte da primeira versão.','Faz parte do escopo…',['cadastro','consulta','lista','mostrar'],'Faz parte do escopo mostrar a lista de tarefas.'),concept('backlog','Backlog','Escreva um item curto do backlog.','Item: …',['criar','permitir','mostrar','adicionar'],'Item: criar tela de cadastro de tarefas.'),concept('scrum','Scrum','Cite um evento curto do Scrum.','Evento: …',['sprint','daily','diária','diaria','planejamento','revisão','retrospectiva'],'Evento: reunião diária.'),concept('kanban','Kanban','Escreva uma coluna de um quadro Kanban.','Coluna: …',['fazer','andamento','conclu','pronto'],'Coluna: Em andamento.'),concept('prototype','Protótipo','Diga o que será representado no protótipo.','O protótipo mostrará…',['tela','fluxo','botão','menu'],'O protótipo mostrará o fluxo de cadastro.'),concept('rf','Requisito funcional','Escreva uma função que o sistema deve realizar.','O sistema deve…',['permitir','calcular','enviar','registrar'],'O sistema deve permitir que o usuário cadastre uma solicitação.'),concept('rnf','Requisito não funcional','Descreva uma qualidade esperada do sistema.','O sistema deve ser…',['rápid','segur','acess','dispon'],'O sistema deve carregar em até dois segundos.'),concept('rule','Regra de negócio','Escreva uma regra que limita uma ação.','Somente…',['somente','não pode','deve','limite'],'Somente professores podem aprovar uma entrega.'),concept('acceptance','Critério de aceitação','Diga como confirmar que uma função está correta.','Quando… então…',['quando','então','deve','exibe'],'Quando o aluno enviar, então o sistema mostra a confirmação.'),concept('trace','Rastreabilidade','Ligue um requisito a uma evidência.','O requisito RF01 está ligado a…',['teste','tela','história','rf'],'O requisito RF01 está ligado ao teste CT01.')];

